# Selecting Rows

### Introduction

Now that we know how to work with a dataframe and select individual columns, it's time for us to see if we can begin to understand the contents of our data by looking at specific rows.

Getting a sense of what kind of data our dataset includes and does not include is a critical step to performing data analysis.  For example, before we calculate the average cost of a flood on someone's home, it's important to know if we are looking at data from just a single city, or state, or year.

And a one way to understand this is to look at a few rows of data.

### Exploring a DataFrame

So let's go back to exploring our flooding data.  The first thing we'll do is load up the data.

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/jigsawlabs-student/pandas-free-curriculum/master/houston_claims.csv"
claims_df = pd.read_csv(url, index_col = 0)
claims_df[:3]

reportedCity                dateOfLoss elevatedBuildingIndicator floodZone  \
0      HOUSTON  2017-08-27T00:00:00.000Z                     False         X   
1      HOUSTON  2008-09-12T00:00:00.000Z                     False         X   
2      HOUSTON  2004-06-29T00:00:00.000Z                     False         X   

   latitude  longitude  lowestFloodElevation  amountPaidOnBuildingClaim  \
0      29.7      -95.5                   NaN                  195857.43   
1      29.5      -95.1                   NaN                       0.00   
2      29.8      -95.6                   NaN                    1420.89   

   amountPaidOnContentsClaim                yearofLoss  reportedZipcode  \
0                        0.0  2017-01-01T00:00:00.000Z            77096   
1                        0.0  2008-01-01T00:00:00.000Z            77058   
2                        0.0  2004-01-01T00:00:00.000Z            77042   

                         id  
0  5e398d6774cbd479fc898dea  
1  5e398d6774cbd479fc898dfc  
2  5e398d6774cbd479fc898e4b

And then we can reacquaint ourselves with the columns available.

In [ ]:
claims_df.columns

Index(['reportedCity', 'dateOfLoss', 'elevatedBuildingIndicator', 'floodZone',
       'latitude', 'longitude', 'lowestFloodElevation',
       'amountPaidOnBuildingClaim', 'amountPaidOnContentsClaim', 'yearofLoss',
       'reportedZipcode', 'id'],
      dtype='object')

### Viewing a subset of rows

Because it may be difficult to understand what information is in these columns, we may want to look at some of the values in a few of the rows. We can do this with the `head` or `tail` methods.

In [2]:
claims_df.head(2)

reportedCity                dateOfLoss elevatedBuildingIndicator floodZone  \
0      HOUSTON  2017-08-27T00:00:00.000Z                     False         X   
1      HOUSTON  2008-09-12T00:00:00.000Z                     False         X   

   latitude  longitude  lowestFloodElevation  amountPaidOnBuildingClaim  \
0      29.7      -95.5                   NaN                  195857.43   
1      29.5      -95.1                   NaN                       0.00   

   amountPaidOnContentsClaim                yearofLoss  reportedZipcode  \
0                        0.0  2017-01-01T00:00:00.000Z            77096   
1                        0.0  2008-01-01T00:00:00.000Z            77058   

                         id  
0  5e398d6774cbd479fc898dea  
1  5e398d6774cbd479fc898dfc

In [3]:
claims_df.tail(2)

reportedCity                dateOfLoss elevatedBuildingIndicator  \
19998      HOUSTON  2016-04-18T00:00:00.000Z                     False   
19999      HOUSTON  2017-08-26T00:00:00.000Z                     False   

      floodZone  latitude  longitude  lowestFloodElevation  \
19998        AE      29.9      -95.5                  94.0   
19999         X      29.7      -95.3                   NaN   

       amountPaidOnBuildingClaim  amountPaidOnContentsClaim  \
19998                   34746.10                    7156.78   
19999                   28863.65                   30000.00   

                     yearofLoss  reportedZipcode                        id  
19998  2016-01-01T00:00:00.000Z            77040  5e398dac74cbd479fc8e448a  
19999  2017-01-01T00:00:00.000Z            77087  5e398dac74cbd479fc8e449b

As we can see, the `head` method shows us from the start of the dataframe going forward, and the `tail` method shows us rows from the bottom of the dataframe going backwards.

### Filtering Rows

Ok, now that we know how to select the first and last rows of data, let's see if we can select rows by a certain criteria.  For example, imagine that we only want to get view the data from a specific zipcode.

Let's try to select the data from zipcode `77096`.

> Here's how we do it.

In [4]:
selected_claims = claims_df[claims_df['reportedZipcode'] == 77096]

In [5]:
selected_claims[:2]

reportedCity                dateOfLoss elevatedBuildingIndicator floodZone  \
0       HOUSTON  2017-08-27T00:00:00.000Z                     False         X   
10      HOUSTON  2017-08-28T00:00:00.000Z                     False         X   

    latitude  longitude  lowestFloodElevation  amountPaidOnBuildingClaim  \
0       29.7      -95.5                   NaN                  195857.43   
10      29.7      -95.5                   NaN                  231888.28   

    amountPaidOnContentsClaim                yearofLoss  reportedZipcode  \
0                        0.00  2017-01-01T00:00:00.000Z            77096   
10                   65814.56  2017-01-01T00:00:00.000Z            77096   

                          id  
0   5e398d6774cbd479fc898dea  
10  5e398d6774cbd479fc898fb4

The above can be quite confusing, as it's really two steps combined.  Let's break it down.

* The first step is to select the reportedZipcode column, and repeatedly ask the question, is the zipcode equal to `77096`.

In [ ]:
claims_df['reportedZipcode'] == 77096

0         True
1        False
2        False
3        False
4        False
         ...  
19995    False
19996    False
19997    False
19998    False
19999    False
Name: reportedZipcode, Length: 20000, dtype: bool

> This returns to us a series of `True` or `False` values for each row of data.

Then, if we pass this series of true or false values into the dataframe, pandas will only return the values for which the value is true, and drop any of the false values.

In [ ]:
is_correct_zip = claims_df['reportedZipcode'] == 77096
zip_claims = claims_df[is_correct_zip]

In [ ]:
zip_claims[:2]

reportedCity                dateOfLoss elevatedBuildingIndicator floodZone  \
0       HOUSTON  2017-08-27T00:00:00.000Z                     False         X   
10      HOUSTON  2017-08-28T00:00:00.000Z                     False         X   

    latitude  longitude  lowestFloodElevation  amountPaidOnBuildingClaim  \
0       29.7      -95.5                   NaN                  195857.43   
10      29.7      -95.5                   NaN                  231888.28   

    amountPaidOnContentsClaim                yearofLoss  reportedZipcode  \
0                        0.00  2017-01-01T00:00:00.000Z            77096   
10                   65814.56  2017-01-01T00:00:00.000Z            77096   

                          id  
0   5e398d6774cbd479fc898dea  
10  5e398d6774cbd479fc898fb4

Let's see this again.  This time selecting those rows where the latitude is 29.5.

> First we select the `latitude` column and ask if the latitude equals 29.5.

In [6]:
claims_df['latitude'] == 29.5

0        False
1         True
2        False
3        False
4        False
         ...  
19995    False
19996    False
19997    False
19998    False
19999    False
Name: latitude, Length: 20000, dtype: bool

Then we can pass this query into our dataframe.

In [7]:
selected_latitude_claims = claims_df[claims_df['latitude'] == 29.5]
selected_latitude_claims[:2]

reportedCity                dateOfLoss elevatedBuildingIndicator floodZone  \
1       HOUSTON  2008-09-12T00:00:00.000Z                     False         X   
34      HOUSTON  2008-09-13T00:00:00.000Z                     False         X   

    latitude  longitude  lowestFloodElevation  amountPaidOnBuildingClaim  \
1       29.5      -95.1                   NaN                       0.00   
34      29.5      -95.1                   NaN                  121524.32   

    amountPaidOnContentsClaim                yearofLoss  reportedZipcode  \
1                        0.00  2008-01-01T00:00:00.000Z            77058   
34                   52966.91  2008-01-01T00:00:00.000Z            77058   

                          id  
1   5e398d6774cbd479fc898dfc  
34  5e398d6774cbd479fc899102

So notice that `claims_df` is listed twice.  Once to query if the latitude is `29.5`, and a second time, to select from `claims_df` where the query has a value of True.

```python
claims_df[claims_df['latitude'] == 29.5]
```

### Summary

In this lesson, we learned some basic methods for exploring data.  We saw how to get an overview of the data in an entire dataframe with the `head`, `tail` methods.

Then we moved onto selecting rows that meet a certain criteria, for example, where the latitude is `29.5`.

```python
claims_df[claims_df['latitude'] == 29.5]
```

We saw that it can be helpful to break down queries like the one above into two steps.  

1. Return a series of True or False values for every observation, answering whether the state equals "TEXAS"

In [8]:
claims_df['latitude'] == 29.5


0        False
1         True
2        False
3        False
4        False
         ...  
19995    False
19996    False
19997    False
19998    False
19999    False
Name: latitude, Length: 20000, dtype: bool

Then, from the `claims_df` dataframe, select the rows where the value above is `True`.

In [9]:
selected_latitude_claims = claims_df[claims_df['latitude'] == 29.5]
selected_latitude_claims[:3]

reportedCity                dateOfLoss elevatedBuildingIndicator floodZone  \
1       HOUSTON  2008-09-12T00:00:00.000Z                     False         X   
34      HOUSTON  2008-09-13T00:00:00.000Z                     False         X   
45      HOUSTON  1998-09-11T00:00:00.000Z                      True        AE   

    latitude  longitude  lowestFloodElevation  amountPaidOnBuildingClaim  \
1       29.5      -95.1                   NaN                       0.00   
34      29.5      -95.1                   NaN                  121524.32   
45      29.5      -95.1                   5.0                       0.00   

    amountPaidOnContentsClaim                yearofLoss  reportedZipcode  \
1                        0.00  2008-01-01T00:00:00.000Z            77058   
34                   52966.91  2008-01-01T00:00:00.000Z            77058   
45                        NaN  1998-01-01T00:00:00.000Z            77058   

                          id  
1   5e398d6774cbd479fc898dfc  
34  5e398d6774cbd479fc899102  
45  5e398d6874cbd479fc8993cf